const actions = {
  LOGIN: 'LOGIN',
  LOGIN_PROGRESS: 'LOGIN_PROGRESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  MOVIE_SUGGESTIONS_LOAD: 'MOVIE_SUGGESTIONS_LOAD'
}

export default actions
